x-client-common: &client-common
  build: .
  image: fedn:latest
  command: ["bash", "-c", "fedn client start --api-url ${API} --token ${CLIENT_TOKEN}"]

services:
  water1:
    <<: *client-common
    volumes:
      - ./data/water1.csv:/app/data/water1.csv
    environment:
      - FILE_NAME=water1.csv

  water2:
    <<: *client-common
    volumes:
      - ./data/water2.csv:/app/data/water2.csv
    environment:
      - FILE_NAME=water2.csv

  grass1:
    <<: *client-common
    volumes:
      - ./data/grass1.csv:/app/data/grass1.csv
    environment:
      - FILE_NAME=grass1.csv

  grass2:
    <<: *client-common
    volumes:
      - ./data/grass2.csv:/app/data/grass2.csv
    environment:
      - FILE_NAME=grass2.csv

      